# Generated by Django 3.0.6 on 2020-05-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainicio', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descricion')),
            ],
        ),
    ]
